clearvars;
PATH='./';
load(strcat(PATH,'joints.mat'));
clear PATH;

% Write lsp joints to CSV file
outfile=fopen('lspet.csv','w');
fprintf(outfile, "image, " + ...
    "pt00_x, pt00_y, pt00_v, " + ...
    "pt01_x, pt01_y, pt01_v, " + ...
    "pt02_x, pt02_y, pt02_v, " + ...
    "pt03_x, pt03_y, pt03_v, " + ...
    "pt04_x, pt04_y, pt04_v, " + ...
    "pt05_x, pt05_y, pt05_v, " + ...
    "pt06_x, pt06_y, pt06_v, " + ...
    "pt07_x, pt07_y, pt07_v, " + ...
    "pt08_x, pt08_y, pt08_v, " + ...
    "pt09_x, pt09_y, pt09_v, " + ...
    "pt10_x, pt10_y, pt10_v, " + ...
    "pt11_x, pt11_y, pt11_v, " + ...
    "pt12_x, pt12_y, pt12_v, " + ...
    "pt13_x, pt13_y, pt13_v\n");
for i=1:length(joints)
    % First, deal with the top-level stuff: filename, frame_sec and vididx
    fprintf(outfile, "im%05d.jpg, ", i);

    curimg=joints(:,:,i);
    for j=1:14
        curjoint = curimg(j,:);
        fprintf(outfile, "%f, %f, %f", curjoint(1), ...
            curjoint(2), curjoint(3));
        if j ~= 14
            fprintf(outfile, ", ");
        else
            fprintf(outfile, "\n");
        end
    end
end

fclose(outfile);

